config/routes.rb
Rails.application.routes.draw do
  
  resources :people 
  resources :game_sets
  
  resources :calculate
  
  get 'high_game/compare'

  get 'high_set/compare'

  get 'home/index'
  get 'enter_scores/index'
  get 'averages/compare'
  get 'game_sets/index'
  get 'people/index'
  get 'people/get_data', :defaults => { :format => 'json' }

  root 'home#index'

end

app/models/game_set.rb
require_relative '../../lib/calculate.rb'

class GameSet < ActiveRecord::Base  
  
  belongs_to :person
  
  after_initialize :setAttr
  
  def setAttr()
    self.total = Calculate.total(self.games) unless destroyed?
    self.average = Calculate.avg(self.games) unless destroyed?
  end
end

app/controllers/game_sets_controller.rb
class GameSetsController < ApplicationController
  before_action :set_game_set, only: [:show, :edit, :update, :destroy]

  # GET /game_sets
  # GET /game_sets.json
  def index
    @game_sets = GameSet.all
    @people = Person.all
  end

  # GET /game_sets/1
  # GET /game_sets/1.json
  def show
  end

  # GET /game_sets/new
  def new
    @game_set = GameSet.new
    @people = Person.all
  end

  # GET /game_sets/1/edit
  def edit
    @people = Person.all
  end

  # POST /game_sets
  # POST /game_sets.json
  def create
    @game_set = GameSet.new(game_set_params)

    respond_to do |format|
      if @game_set.save
        format.html { redirect_to new_game_set_url, notice: 'Game set was successfully created.' }
        format.json { render :show, status: :created, location: @game_set }
      else
        format.html { render :new }
        format.json { render json: @game_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_sets/1
  # PATCH/PUT /game_sets/1.json
  def update
    respond_to do |format|
      if @game_set.update(game_set_params)
        format.html { redirect_to @game_set, notice: 'Game set was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_set }
      else
        format.html { render :edit }
        format.json { render json: @game_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_sets/1
  # DELETE /game_sets/1.json
  def destroy
    @game_set.destroy
    respond_to do |format|
      format.html { redirect_to game_sets_url, notice: 'Game set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_set
      @game_set = GameSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_set_params
      #params.fetch(:game_set, {})
      params.require(:game_set).permit(:person_id, :date, :games => [])
    end
end

app/helpers/game_sets_helper.rb
module GameSetsHelper
end

app/views/game_sets/_form.html.erb
<%= form_for(@game_set) do |f| %>
  <% if @game_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game_set.errors.count, "error") %> prohibited this game_set from being saved:</h2>

      <ul>
      <% @game_set.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Date<br>
    <%= f.text_field :date, :id=>"datepicker" %>
  </div>
  <div class="field">
    Game 1<br>
    <%= f.number_field :games, :id=>"g1", within: 0..300, multiple: true %>
  </div>
  <div class="field">
    Game 2<br>
    <%= f.number_field :games, :id=>"g2", within: 0..300, multiple: true %>
  </div>
  <div class="field">
    Game 3<br>
    <%= f.number_field :games, :id=>"g3", within: 0..300, multiple: true %>
  </div>
  
  <div class="field">
  	Select Bowler<br>
  <%= f.collection_select :person_id, @people, :id, :full_name, include_blank: false %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
  <style type="text/css">
.ui-datepicker {
    background: #333;
    border: 1px solid #555;
    color: #EEE;
}
</style>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#datepicker" ).datepicker({dateFormat: "yy-mm-dd"});
  } );
  </script>

app/views/game_sets/edit.html.erb
<div class="centerBox">
<h1>Editing Game Set</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_set %> |
<%= link_to 'Back', game_sets_path %>
</div>

app/views/game_sets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Game Sets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_sets.each do |game_set| %>
      <tr>
      	<td><%= game_set.games %></td>
        <td><%= game_set.total %></td>
        <td><%= game_set.average %></td>
        <td><%= game_set.date %></td>
        <td><%= game_set.person_id %></td>
        <td><%= Person.find(game_set.person_id).full_name if game_set.person_id %></td>
        <td><%= link_to 'Show', game_set %></td>
        <td><%= link_to 'Edit', edit_game_set_path(game_set) %></td>
        <td><%= link_to 'Destroy', game_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/game_sets/new.html.erb
<h1>Enter Scores</h1>

<%= render 'form' %>

<p>Total Pins: <span id="tot"></span></p>
<p>Average: <span id="avg"></span></p>

</div>

<script type="text/javascript"> 
  $("form").on("keyup", function() {
  	var games = [parseInt(document.getElementById("g1").value), 
  				 parseInt(document.getElementById("g2").value), 
  				 parseInt(document.getElementById("g3").value)]
  	var sum = total(games)
  	var avg = average(games)
	document.getElementById("tot").innerHTML = sum;
	document.getElementById("avg").innerHTML = avg;
  });
  function total(games) {
  	var filtered = filterArr(games)
  	return filtered.reduce(function(a, b) { return a + b; }, 0);
  } 
  function average(games) {
  	var sum = total(games)
  	var filtered = filterArr(games)
  	return parseFloat(Math.round((sum / filtered.length) * 100) / 100).toFixed(2);
  }
  function filterArr(arr) {
  	return arr.filter(Number);
  }
</script>

app/views/game_sets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_game_set_path(@game_set) %> |
<%= link_to 'Back', game_sets_path %>