config/routes.rb
Rails.application.routes.draw do
  
  resources :people 
  resources :game_sets
  
  resources :calculate
  
  get 'high_game/compare'

  get 'high_set/compare'

  get 'home/index'
  get 'enter_scores/index'
  get 'averages/compare'
  get 'game_sets/index'
  get 'people/index'
  get 'people/get_data', :defaults => { :format => 'json' }

  root 'home#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :game_sets, :dependent => :delete_all
  
  scope :ordered_by_last_name, -> { order(last_name: :asc) }
  
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all.ordered_by_last_name
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])
    @sorted = @person.game_sets.sort_by &:date
    
    #Get individual game averages
    @games1 = []
    @games2 = []
    @games3 = []
    @total = []
    @person.game_sets.each do |game_set|
      @games1 << game_set.games[0]
      @games2 << game_set.games[1]
      @games3 << game_set.games[2]
      @total << game_set.total
      
    end
    @game1_avg = Calculate.avg(@games1)
    @game2_avg = Calculate.avg(@games2)
    @game3_avg = Calculate.avg(@games3)
    
    #Get total pins of all time
    @total_pins = Calculate.total(@total)
    
    @dates = []
    @avgs = []
    @totals = []
    @sorted.each do |set|
      @dates << set.date
      @avgs << set.average
      @totals << set.total
    end
    
  end      

  def get_data
    @person = Person.find(params[:id])
    @sorted = @person.game_sets.sort_by &:date
    
    @dates = []
    @avgs = []
    @totals = []
    @sorted.each do |set|
      @dates << set.date
      @avgs << set.average
      @totals << set.total
    end
    
    respond_to do |format|
      format.json { render :json => { :dates => @dates,
                                      :avgs => @avgs,
                                      :totals => @totals } }
    end
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :gender)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name, 'First Name' %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name, 'Last Name' %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/_graph_stats.html.erb

<style>
	line {
  		stroke: black;
	}

	path {
    	fill: none;
    	stroke: green;
	}

</style>

<svg style="background-color: white"></svg>

<script src="https://d3js.org/d3.v3.min.js"></script>
<script>
	var dates = <%= @dates %>, 
		avgs = <%= @avgs %>,
		totals = <%= @totals %>
	
	var data = dates.map(function(d, i){
 		return { 'date' : d, 'average' : avgs[i], 'total' : totals[i] };
	};
	
	var parseTime = d3.timeParse("%Y-%m-%d");

    var w = 450,
    h = 275,
    p = 30,
    y = d3.scale.linear().domain([0, 300]).range([h, 0]),
    x = d3.time.scale().domain(d3.extent(data, function(d) { return d.date; })).range([0, w]);

    var vis = d3.select("body")
    .append("svg")
    .attr("width", w + p * 2)
    .attr("height", h + p * 2)
    .append("g")
    .attr("transform", "translate(" + p + "," + p + ")");

    var rules = vis.selectAll("g.rule")
    .data(x.ticks(5))
    .enter().append("g")
    .attr("class", "rule");

    rules.append("line")
    .attr("x1", x)
    .attr("x2", x)
    .attr("y1", 0)
    .attr("y2", h - 1);

    rules.append("line")
    .attr("class", function(d) { return d.average ? null : "axis"; })
    .attr("y1", y)
    .attr("y2", y)
    .attr("x1", 0)
    .attr("x2", w + 1);

    rules.append("text")
    .attr("x", x)
    .attr("y", h + 3)
    .attr("dy", ".71em")
    .attr("text-anchor", "middle")
    .text(x.tickFormat(10));

    rules.append("text")
    .attr("y", y)
    .attr("x", -3)
    .attr("dy", ".35em")
    .attr("text-anchor", "end")
    .text(y.tickFormat(10));

    vis.append("path")
    .data([data])
    .attr("class", "line")
    .attr("d", d3.svg.line()
        .x(function(d) { return x(parseTime(d.date)) })
        .y(function(d) { return y(d.average) })
    );

    vis.selectAll("circle.line")
    .data(data)
    .enter().append("circle")
    .attr("class", "line")
    .attr("cx", function(d) { return x(parseTime(d.date)) })
    .attr("cy", function(d) { return y(d.average); })
    .attr("r", 3.5);
    
</script>
	

app/views/people/_table_stats.html.erb
<table border="1">
	<tr>
      <th>Date</th>
      <th>Game 1</th>
      <th>Game 2</th>
      <th>Game 3</th>
      <th>Total</th>
      <th>Average</th>
      <th>Overall Average</th>
    </tr>
    <% @overall_avg = [] %>
    <% @sorted.each do |game_set| %>
    <tr>
    	<td><%= game_set.date %></td>
    	<td><%= game_set.games[0] %></td>
    	<td><%= game_set.games[1] %></td>
    	<td><%= game_set.games[2] %></td>
    	<td><%= game_set.total %></td>
    	<td><%= game_set.average %></td>
    	<td><% @overall_avg << game_set.average %>
    		<%= Calculate.avg(@overall_avg) %></td>
    </tr>
    <% end %>
</table>

<p>Average By Game</p>
<p>Game 1: <%= @game1_avg %> | Game 2: <%= @game2_avg %> | Game 3: <%= @game3_avg %></p>

<p>Total Pins: <%= @total_pins %></p>
<p>Overall Average: <%= Calculate.avg(@overall_avg) %></p>

app/views/people/edit.html.erb
<div class="centerBox">
<h1>Edit Bowler</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>
</div>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>
<h1>List of Users</h1>

<table border="1">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.gender %></td>
        <td><%= link_to 'Edit User', edit_person_path(person) %></td>
        <td><%= link_to 'User Stats', person %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bowler', new_person_path %>

app/views/people/new.html.erb
<div class="centerBox">
<h1>New Bowler</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>
</div>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @person.gender %>
</p>

<p>Display Stats in table or graphically? 
<%= select_tag :viz, options_for_select([ "Table", "Graph" ], selected: "Table"),
      :onchange => "compareFunc(this.options[this.selectedIndex].value); return false;" %>
</p>

<div class="table_stats">
<%= render 'table_stats' %>
</div>

<div class="graph_stats">
<%= render 'graph_stats' %>
</div>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

<script type="text/javascript"> 
  function compareFunc(x) {
		if (x == "Table") {
			$('.table_stats').show();
			$('.graph_stats').hide();
		}
		else if (x == "Graph") {
			$('.graph_stats').show();
			$('.table_stats').hide();
		}
	};
</script>