config/routes.rb
Rails.application.routes.draw do
  
  resources :people 
  resources :game_sets
  
  resources :calculate
  
  get 'high_game/compare'

  get 'high_set/compare'

  get 'home/index'
  get 'enter_scores/index'
  get 'averages/compare'
  get 'game_sets/index'
  get 'people/index'
  get 'people/get_data', :defaults => { :format => 'json' }

  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BowlService</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="centerfold">
 
  <div class="titleBox">
    <div class="title">Welcome to SPUR w/ Bowling</div>
  
    <div class="homeBar">
    	<p><%= link_to "Home", root_path,  :class => "link" %>
    		 | Username PH | Logout PH</p>
  	  <!--<p><%= link_to "User List", people_path, :method => "get", :class => "link" %>
         <%= link_to "Enter New Scores", new_game_set_path, :method => "get", :class => "link" %></p>-->
    </div>
  </div>

<div class="actionBar">
	<%= link_to "User List", people_path, :method => "get" %>
	|
	<%= link_to "Enter New Scores", new_game_set_path(:person_id), :method => "get" %>
	|
	<%= link_to "Compare Averages", averages_compare_path, :method => "get" %>
	|
	<%= link_to "Compare High Scores", high_game_compare_path, :method => "get" %>
	|
	<%= link_to "Compare High Sets", high_set_compare_path, :method => "get" %>
</div>

<p id="notice"><%= notice %></p>
<%= yield %>

</body>
</html>